apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWU1HdUdzbTh1MkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMU1qSXhNREl4TXpOYUZ3MHpOVEExTWpBeE1ESTJNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNucXN0WU1IVWhTamo5dVExYmd4UTFackFEakNiV3RhbHNnQUpOWTA5b1lyamQweVZqeGt2MndnQzYKdGM0bkQrYmozRU1GbDZTSXJMVDMyMy85TEdxczJGdmFSS3NnclVPV08vUnd5c1dGMVZxZGJ3QUUrblhEOXNDUQplWjk3NXJlMFd3bmJDRUhPSVdQT0drVWFhQ2p0c3FXNG5YZzlCZnJ1K1ZlaEdWUm81Uk1XaEZwL2MvMTJXZUE2CkY5QTMwNEk1R1FLbFpyUnB3L0pCR2VJUTBMcXk5bVlFYUh1U3NjNVMyTTVnQ0hhc3FSb1BkbGlXWjl0N20wZ0YKQ1hQMmJZenNySGlwcXM5S2tUVGhNSXJMVVNFRU9rdHc1R3RNNzZFWHA4K01INXp6SXA0Um9EZk05RUxPeHZmWApBSFZnRXQvVzg4QXJKYzFIdU4vWkhMMHBZY3VqQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJScjM1VWgyOFU1L3h1S0hDY0ZrRFRqY3FwcXVUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnpENlpQYzRLTAp1NWZlT2RURDlOa1pWRnhjYW1LL21yN2dyRmp5S2FvN2FxTnlaZUpLMWM2bEFnLzVBeTdEeHkra1V6NmlMbDB5CmJYcUpBZHRsTzdSc2M5cHA0eWJLSUFpVkx3bjJmcEwwVUxNRS8xOGdhbk1PTU12VDdxdXBrcW8xcVNWK2hkYncKL2lNdnR3VGFMVFdCL2xZYjhKaXBSclVwWk1rNDdWN0dBQkxJbTRZRXVlTHF5dnRSTFcwQVNwcDRScytJdlVkWQpzaloyYkcxZk5UQmMyaHJ1c0J2Q3NPMTlydVRIZWJmRmJIQU5sb2xBUGFFS3ZFa01FeUlqVmZzNENyb203YTRzCm1XT0FMR1hUekZhMk8xZ2dwQy8vdDBRcmo3Vlo2aFo1S0YwOUhOYkNIR0JXVG1yWGIzL2NJRTlJZi9UQUU1SjIKK1pSM2dWdmN6RGdjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://70E9966B2BE889ECCFE79456A3A640A8.sk1.eks-cluster.eu-central-1.api.aws
  name: arn:aws:eks:eu-central-1:254992224593:cluster/eset-demo-eks-ipv6
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:254992224593:cluster/eset-demo-eks-ipv6
    user: arn:aws:eks:eu-central-1:254992224593:cluster/eset-demo-eks-ipv6
  name: arn:aws:eks:eu-central-1:254992224593:cluster/eset-demo-eks-ipv6
current-context: arn:aws:eks:eu-central-1:254992224593:cluster/eset-demo-eks-ipv6
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:254992224593:cluster/eset-demo-eks-ipv6
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - eset-demo-eks-ipv6
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: ESET_POC
