apiVersion: v1
kind: Service
metadata:
  name: {{.Values.eapi.metadata.name}}
spec:
  selector:
    app: {{.Values.eapi.metadata.name}}
  ports:
    - protocol: TCP
      port: {{.Values.eapi.port}}
      targetPort: {{.Values.eapi.targetPort}}