schedules:
  - cron: "0 3 * * *"
    displayName: "Every day at 3am" # Adjust schedule if needed
    branches:
      include: [main]

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: "EXAMPLE-PROJECT-RENOVATEBOT"

steps:
  - bash: |
      git config --global user.email 'bot@renovateapp.com'
      git config --global user.name 'Renovate Bot'
      npx renovate      
    env:
      TOKEN: $(System.AccessToken)
      GITHUB_COM_TOKEN: $(githubtoken) # get a token from https://github.com/settings/tokens and save it in the 'renovatebot' variables group
      RENOVATE_CONFIG_FILE: "./renovate/config.js"
    