FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN update-ca-certificates

RUN pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --no-cache-dir --upgrade -r /code/requirements.txt 

COPY ./app /code/app


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
